apiVersion: v1
# This configmap is used to define the env variables that Mastodon uses. 
kind:  ConfigMap
metadata:
  name: mastodon-env
data:
  # DB Config
  POSTGRES_USER: "mastodon"
  POSTGRES_PASS: <YOUR-POSTGRES-USER-PASSWORD>
  POSTGRES_MASTER_PASS: <YOUR-POSTGRES-MASTER-PASSWORD>
  POSTGRES_DB: "mastodon_production"
  DB_PORT: "5432"
  DB_HOST: "localhost"
  # Site Config
  SECRET_KEY_BASE: "<YourGeneratedSecretKeyBase>"
  OTP_SECRET: "<YourGeneratedOTPSecret>"
  LOCAL_DOMAIN: "social.example.com"
  IP_RETENTION_PERIOD: "31556952"
  SESSION_RETENTION_PERIOD: "31556952"
  VAPID_PUBLIC_KEY: "<YourGeneratedVAPIDKey>"
  VAPID_PRIVATE_KEY: "<YourGeneratedVAPIDPrivateKey>"
  AUTHORIZED_FETCH: false
  # Mail Config, SMTP settings explnations here: https://docs.joinmastodon.org/admin/config/#email
  SMTP_FROM_ADDRESS: "notifications@example.com"
  SMTP_PORT: "587"
  SMTP_SERVER: "smtp.mailgun.org"
  SMTP_DELIVERY_METHOD: "smtp"
#  SMTP_OPENSSL_VERIFY_MODE: "none"
#  SMTP_ENABLE_STARTTLS_AUTO: "false"
#  SMTP_TLS: "false"
#  SMTP_SSL: "false"
# Redis Config
  REDIS_HOST: "127.0.0.1"
  REDIS_PORT: "6379"
  
