# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.1.1
# Note:
#  This I have cleaned the identifying information out of this file, so it can be shared as a base for other mastodon deployments.
#  A few things: 
#    - The various container images are locked to specific versions, this was suggested by the how-to I followed (linked on the next line) when standing up Mastodon
#      - HOWTO: https://www.linode.com/docs/guides/install-mastodon-server-on-centos-stream/
#    - You'll want to look up the latest versions of mastodon, redis, and postgres, and adjust accordingly.  
#    - There are various environment settings.  You may be able to de-dupliucate these, they ended up tied to every mastodon container (as there are several for different purposes)
#      - These variables are the config for your mastodon instance, you WILL need to modify them.  Ive tried to make them easy to identify.
#    - The howto above also uses some static content from the mastodon git repo, you will need to incorporate that somehow, I put these containers behind nginx
#       - nginx hosts that static content for me, and proxies to the containers.  You'll have to deal with that in kube if thats your goal.
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/db: container
    io.kubernetes.cri-o.ContainerType/redis: container
    io.kubernetes.cri-o.ContainerType/sidekiq: container
    io.kubernetes.cri-o.ContainerType/streaming: container
    io.kubernetes.cri-o.ContainerType/web: container
    io.kubernetes.cri-o.SandboxID/db: mastodon
    io.kubernetes.cri-o.SandboxID/redis: mastodon
    io.kubernetes.cri-o.SandboxID/sidekiq: mastodon
    io.kubernetes.cri-o.SandboxID/streaming: mastodon
    io.kubernetes.cri-o.SandboxID/web: mastodon
    io.kubernetes.cri-o.TTY/db: "false"
    io.kubernetes.cri-o.TTY/redis: "false"
    io.kubernetes.cri-o.TTY/sidekiq: "false"
    io.kubernetes.cri-o.TTY/streaming: "false"
    io.kubernetes.cri-o.TTY/web: "false"
    io.podman.annotations.autoremove/db: "FALSE"
    io.podman.annotations.autoremove/redis: "FALSE"
    io.podman.annotations.autoremove/sidekiq: "FALSE"
    io.podman.annotations.autoremove/streaming: "FALSE"
    io.podman.annotations.autoremove/web: "FALSE"
    io.podman.annotations.init/db: "FALSE"
    io.podman.annotations.init/redis: "FALSE"
    io.podman.annotations.init/sidekiq: "FALSE"
    io.podman.annotations.init/streaming: "FALSE"
    io.podman.annotations.init/web: "FALSE"
    io.podman.annotations.privileged/db: "FALSE"
    io.podman.annotations.privileged/redis: "FALSE"
    io.podman.annotations.privileged/sidekiq: "FALSE"
    io.podman.annotations.privileged/streaming: "FALSE"
    io.podman.annotations.privileged/web: "FALSE"
    io.podman.annotations.publish-all/db: "FALSE"
    io.podman.annotations.publish-all/redis: "FALSE"
    io.podman.annotations.publish-all/sidekiq: "FALSE"
    io.podman.annotations.publish-all/streaming: "FALSE"
    io.podman.annotations.publish-all/web: "FALSE"
  creationTimestamp: "2022-11-04T02:00:31Z"
  labels:
    app: mastodon
  name: mastodon
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_USER
      value: mastodon
    - name: POSTGRES_PASSWORD
      value: <Your Desired Postgres Password>
    - name: POSTGRES_DB
      value: mastodon_production
    image: docker.io/library/postgres:9.6-alpine
    name: db
    ports:
    - containerPort: 3000
      hostPort: 3000
    - containerPort: 4000
      hostPort: 4000
    - containerPort: 9200
      hostPort: 9200
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: mastodon-vol-db-pvc
  - args:
    - redis-server
    image: docker.io/library/redis:6.0-alpine
    name: redis
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /data
      name: mastodon-vol-redis-pvc
  - command: ['node']
    args: ['./streaming']
    env:
    - name: DB_USER
      value: mastodon
    - name: SMTP_FROM_ADDRESS
      value: <your notification FROM address, example notifications@example.org> 
    - name: SECRET_KEY_BASE
      value: <Key generated by mastodon, see howto above>
    - name: LOCAL_DOMAIN
      value: <your mastodon host name>
    - name: REDIS_HOST
      value: 127.0.0.1 
    - name: IP_RETENTION_PERIOD
      value: "31556952"
    - name: DB_PORT
      value: "5432"
    - name: DB_HOST
      value: 127.0.0.1 
    - name: DB_NAME
      value: mastodon_production
    - name: DB_PASS
      value: <Your desired postgres password>
    - name: REDIS_PORT
      value: "6379"
      # SMTP settings explnations here: https://docs.joinmastodon.org/admin/config/#email
    - name: SMTP_PORT
      value: "587"
    - name: SMTP_SSL
      value: false
    - name: SMTP_TLS
      value: false
    - name: SMTP_ENABLE_STARTTLS_AUTO
      value: false
    - name: SMTP_OPENSSL_VERIFY_MODE
      value: none
    - name: SMTP_DELIVERY_METHOD
      value: smtp
    - name: SESSION_RETENTION_PERIOD
      value: "31556952"
    - name: VAPID_PUBLIC_KEY
      value: <generated by mastodon, see howto listed above>
    - name: SMTP_SERVER
      value: <your smtp relay address
    - name: VAPID_PRIVATE_KEY
      value: <generated by mastodon, see howto listed above>
    - name: OTP_SECRET
      value: <generated by mastodon, see howto listed above>
    image: docker.io/tootsuite/mastodon:v3.5.3
    name: streaming
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
  - command: ['bundle']
    args: ['exec', 'sidekiq']
    env:
    - name: DB_USER
      value: mastodon
    - name: SMTP_FROM_ADDRESS
      value: <your notification FROM address, example notifications@example.org> 
    - name: SECRET_KEY_BASE
      value: <Key generated by mastodon, see howto above>
    - name: LOCAL_DOMAIN
      value: <your mastodon host name>
    - name: REDIS_HOST
      value: 127.0.0.1 
    - name: IP_RETENTION_PERIOD
      value: "31556952"
    - name: DB_PORT
      value: "5432"
    - name: DB_HOST
      value: 127.0.0.1 
    - name: DB_NAME
      value: mastodon_production
    - name: DB_PASS
      value: <Your desired postgres password>
    - name: REDIS_PORT
      value: "6379"
      # SMTP settings explnations here: https://docs.joinmastodon.org/admin/config/#email
    - name: SMTP_PORT
      value: "587"
    - name: SMTP_SSL
      value: false
    - name: SMTP_TLS
      value: false
    - name: SMTP_ENABLE_STARTTLS_AUTO
      value: false
    - name: SMTP_OPENSSL_VERIFY_MODE
      value: none
    - name: SMTP_DELIVERY_METHOD
      value: smtp
    - name: SESSION_RETENTION_PERIOD
      value: "31556952"
    - name: VAPID_PUBLIC_KEY
      value: <generated by mastodon, see howto listed above>
    - name: SMTP_SERVER
      value: <your smtp relay address
    - name: VAPID_PRIVATE_KEY
      value: <generated by mastodon, see howto listed above>
    - name: OTP_SECRET
      value: <generated by mastodon, see howto listed above>
    image: docker.io/tootsuite/mastodon:v3.5.3
    name: sidekiq
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /mastodon/public/system
      name: mastodon-vol-pubsys-pvc

  - command: ['/bin/bash']
    args: ["-c", "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"]
    env:
    - name: DB_USER
      value: mastodon
    - name: SMTP_FROM_ADDRESS
      value: <your notification FROM address, example notifications@example.org> 
    - name: SECRET_KEY_BASE
      value: <Key generated by mastodon, see howto above>
    - name: LOCAL_DOMAIN
      value: <your mastodon host name>
    - name: REDIS_HOST
      value: 127.0.0.1 
    - name: IP_RETENTION_PERIOD
      value: "31556952"
    - name: DB_PORT
      value: "5432"
    - name: DB_HOST
      value: 127.0.0.1 
    - name: DB_NAME
      value: mastodon_production
    - name: DB_PASS
      value: <Your desired postgres password>
    - name: REDIS_PORT
      value: "6379"
      # SMTP settings explnations here: https://docs.joinmastodon.org/admin/config/#email
    - name: SMTP_PORT
      value: "587"
    - name: SMTP_SSL
      value: false
    - name: SMTP_TLS
      value: false
    - name: SMTP_ENABLE_STARTTLS_AUTO
      value: false
    - name: SMTP_OPENSSL_VERIFY_MODE
      value: none
    - name: SMTP_DELIVERY_METHOD
      value: smtp
    - name: SESSION_RETENTION_PERIOD
      value: "31556952"
    - name: VAPID_PUBLIC_KEY
      value: <generated by mastodon, see howto listed above>
    - name: SMTP_SERVER
      value: <your smtp relay address
    - name: VAPID_PRIVATE_KEY
      value: <generated by mastodon, see howto listed above>
    - name: OTP_SECRET
      value: <generated by mastodon, see howto listed above>
    image: docker.io/tootsuite/mastodon:v3.5.3
    name: web
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /mastodon/public/system
      name: mastodon-vol-pubsys-pvc
  restartPolicy: Never
  # Volumes for the various data you need persistent.  I used NFS volumes, you can use whatever, just make sure the names match what you define below
  volumes:
  - name: mastodon-vol-db-pvc
    persistentVolumeClaim:
      claimName: mastodon-vol-db
  - name: mastodon-vol-redis-pvc
    persistentVolumeClaim:
      claimName: mastodon-vol-redis
  - name: mastodon-vol-pubsys-pvc
    persistentVolumeClaim:
      claimName: mastodon-vol-pubsys

status: {}

