apiVersion: v1
# This configmap is used to define the env variables that Mastodon uses. 
# In podman, i can't seem to just pass all variables to a container, so I had to map them all in the container definitions
# If you add a new variable here, or uncomment one, you will need to add or uncommet them in the mastodon-pod.yaml as well. 
#    Each container has an env definition, with mappings for env to keys.  You will need to add those to each container that needs your new variable.
#    This was the cleanest way I could get this done in podman.  
kind:  ConfigMap
metadata:
  name: mastodon-env
data:
  # DB Config
  POSTGRES_USER: "mastodon"
  POSTGRES_PASS: "<YourDBPassword>"
  POSTGRES_MASTER_PASS: "<yourMasterPassword>"
  POSTGRES_DB: "mastodon_production"
  DB_PORT: "5432"
  DB_HOST: "localhost"
  # Site Config
  SECRET_KEY_BASE: "<YourGeneratedSecretKeyBase>"
  OTP_SECRET: "<YourGeneratedOTPSecret>"
  LOCAL_DOMAIN: "social.example.com"
  IP_RETENTION_PERIOD: "31556952"
  SESSION_RETENTION_PERIOD: "31556952"
  VAPID_PUBLIC_KEY: "<YourGeneratedVAPIDKey>"
  VAPID_PRIVATE_KEY: "<YourGeneratedVAPIDPrivateKey>"
  # Mail Config, SMTP settings explnations here: https://docs.joinmastodon.org/admin/config/#email
  SMTP_FROM_ADDRESS: "notifications@example.com"
  SMTP_PORT: "587"
  SMTP_SERVER: "smtp.mailgun.org"
  SMTP_DELIVERY_METHOD: "smtp"
#  SMTP_OPENSSL_VERIFY_MODE: "none"
#  SMTP_ENABLE_STARTTLS_AUTO: "false"
#  SMTP_TLS: "false"
#  SMTP_SSL: "false"
  # Redis Cnfig
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  